//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rawer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rawer.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string AboutPageAppBarEmail {
            get {
                return ResourceManager.GetString("AboutPageAppBarEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string AboutPageAppBarFeedback {
            get {
                return ResourceManager.GetString("AboutPageAppBarFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rawerapp@gmail.com.
        /// </summary>
        public static string AboutPageEmail {
            get {
                return ResourceManager.GetString("AboutPageEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rawer feedback.
        /// </summary>
        public static string AboutPageEmailSubject {
            get {
                return ResourceManager.GetString("AboutPageEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact email:.
        /// </summary>
        public static string AboutPageEmailText {
            get {
                return ResourceManager.GetString("AboutPageEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open and edit RAW Camera photos.
        ///
        ///Notice: Due to memory limitation on low memory phones, the app can open large images in half size..
        /// </summary>
        public static string AboutPageMainText {
            get {
                return ResourceManager.GetString("AboutPageMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks to:
        ///•	Bruno Blanes (tradução para o Português)
        ///•	Muntadhar Haydar (translation to Arabic)
        ///•	Richard Yates (usefull tips and photo samples).
        /// </summary>
        public static string AboutPageThanksText {
            get {
                return ResourceManager.GetString("AboutPageThanksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AboutPageVersionText {
            get {
                return ResourceManager.GetString("AboutPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string BlurTool {
            get {
                return ResourceManager.GetString("BlurTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string BrightnessTool {
            get {
                return ResourceManager.GetString("BrightnessTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFECTS.
        /// </summary>
        public static string ColorEffectsTool {
            get {
                return ResourceManager.GetString("ColorEffectsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string CommonSizeB {
            get {
                return ResourceManager.GetString("CommonSizeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string CommonSizeGB {
            get {
                return ResourceManager.GetString("CommonSizeGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string CommonSizeKB {
            get {
                return ResourceManager.GetString("CommonSizeKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string CommonSizeMB {
            get {
                return ResourceManager.GetString("CommonSizeMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        public static string ContrastTool {
            get {
                return ResourceManager.GetString("ContrastTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string CropTool {
            get {
                return ResourceManager.GetString("CropTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, something going wrong. Sorry for that. Im giving you a word that it will be fixed if you send us error report by pressing OK button. Thanks in advance.  .
        /// </summary>
        public static string DiagnosticEmailBody {
            get {
                return ResourceManager.GetString("DiagnosticEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error.
        /// </summary>
        public static string DiagnosticEmailTitle {
            get {
                return ResourceManager.GetString("DiagnosticEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string EditPageProgressBarWorking {
            get {
                return ResourceManager.GetString("EditPageProgressBarWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure.
        /// </summary>
        public static string ExposureTool {
            get {
                return ResourceManager.GetString("ExposureTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        public static string HighlightsTool {
            get {
                return ResourceManager.GetString("HighlightsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string HueTool {
            get {
                return ResourceManager.GetString("HueTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        public static string ImageInfoPageAperture {
            get {
                return ResourceManager.GetString("ImageInfoPageAperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string ImageInfoPageAuthor {
            get {
                return ResourceManager.GetString("ImageInfoPageAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ImageInfoPageDescription {
            get {
                return ResourceManager.GetString("ImageInfoPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        public static string ImageInfoPageFlash {
            get {
                return ResourceManager.GetString("ImageInfoPageFlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        public static string ImageInfoPageFlashAuto {
            get {
                return ResourceManager.GetString("ImageInfoPageFlashAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal.
        /// </summary>
        public static string ImageInfoPageFocal {
            get {
                return ResourceManager.GetString("ImageInfoPageFocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string ImageInfoPageHeight {
            get {
                return ResourceManager.GetString("ImageInfoPageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string ImageInfoPageISO {
            get {
                return ResourceManager.GetString("ImageInfoPageISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ImageInfoPageLocation {
            get {
                return ResourceManager.GetString("ImageInfoPageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture.
        /// </summary>
        public static string ImageInfoPageManufacture {
            get {
                return ResourceManager.GetString("ImageInfoPageManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string ImageInfoPageModel {
            get {
                return ResourceManager.GetString("ImageInfoPageModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MP.
        /// </summary>
        public static string ImageInfoPageMp {
            get {
                return ResourceManager.GetString("ImageInfoPageMp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ImageInfoPageName {
            get {
                return ResourceManager.GetString("ImageInfoPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string ImageInfoPageNo {
            get {
                return ResourceManager.GetString("ImageInfoPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string ImageInfoPageSec {
            get {
                return ResourceManager.GetString("ImageInfoPageSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shot order.
        /// </summary>
        public static string ImageInfoPageShotOrder {
            get {
                return ResourceManager.GetString("ImageInfoPageShotOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter.
        /// </summary>
        public static string ImageInfoPageShutter {
            get {
                return ResourceManager.GetString("ImageInfoPageShutter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ImageInfoPageSize {
            get {
                return ResourceManager.GetString("ImageInfoPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size on disk.
        /// </summary>
        public static string ImageInfoPageSizeOnDisk {
            get {
                return ResourceManager.GetString("ImageInfoPageSizeOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        public static string ImageInfoPageSoftware {
            get {
                return ResourceManager.GetString("ImageInfoPageSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string ImageInfoPageTime {
            get {
                return ResourceManager.GetString("ImageInfoPageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ImageInfoPageTitle {
            get {
                return ResourceManager.GetString("ImageInfoPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string ImageInfoPageWidth {
            get {
                return ResourceManager.GetString("ImageInfoPageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string ImageInfoPageYes {
            get {
                return ResourceManager.GetString("ImageInfoPageYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like something wrong with your file. Sorry for that. Maybe it was corrupted during downloading try to re load it..
        /// </summary>
        public static string LIBRAW_COMMON_ERROR_text {
            get {
                return ResourceManager.GetString("LIBRAW_COMMON_ERROR_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string LIBRAW_COMMON_ERROR_title {
            get {
                return ResourceManager.GetString("LIBRAW_COMMON_ERROR_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like this type of raw photo is not supported yet. Sorry for that we will try to fix that..
        /// </summary>
        public static string LIBRAW_FILE_UNSUPPORTED_Text {
            get {
                return ResourceManager.GetString("LIBRAW_FILE_UNSUPPORTED_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported file type.
        /// </summary>
        public static string LIBRAW_FILE_UNSUPPORTED_Title {
            get {
                return ResourceManager.GetString("LIBRAW_FILE_UNSUPPORTED_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like there is not enough memory on your device. Sorry for that. Try to open a smaller image..
        /// </summary>
        public static string LIBRAW_UNSUFFICIENT_MEMORY_text {
            get {
                return ResourceManager.GetString("LIBRAW_UNSUFFICIENT_MEMORY_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory.
        /// </summary>
        public static string LIBRAW_UNSUFFICIENT_MEMORY_title {
            get {
                return ResourceManager.GetString("LIBRAW_UNSUFFICIENT_MEMORY_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string MainPageAppBarCheckMode {
            get {
                return ResourceManager.GetString("MainPageAppBarCheckMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MainPageAppBarDelete {
            get {
                return ResourceManager.GetString("MainPageAppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grid.
        /// </summary>
        public static string MainPageAppBarLayoutGrid {
            get {
                return ResourceManager.GetString("MainPageAppBarLayoutGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string MainPageAppBarLayoutList {
            get {
                return ResourceManager.GetString("MainPageAppBarLayoutList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        public static string MainPageAppBarOpen {
            get {
                return ResourceManager.GetString("MainPageAppBarOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Roll.
        /// </summary>
        public static string MainPageFolderName {
            get {
                return ResourceManager.GetString("MainPageFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for .dng files in Camera Roll.
        /// </summary>
        public static string MainPageListBoxEmptyContent {
            get {
                return ResourceManager.GetString("MainPageListBoxEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string MainPageListBoxSearching {
            get {
                return ResourceManager.GetString("MainPageListBoxSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open file.
        /// </summary>
        public static string MainPageMainButton {
            get {
                return ResourceManager.GetString("MainPageMainButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like there is no .DNG files in Camera roll. You can go to camera settings and switch on capture mode option to &quot;jpeg+DNG&quot;
        ///
        ///
        ///
        ///or select file from another location.
        /// </summary>
        public static string MainPageNoDNGFiles {
            get {
                return ResourceManager.GetString("MainPageNoDNGFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOISE.
        /// </summary>
        public static string NoiseTool {
            get {
                return ResourceManager.GetString("NoiseTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its extremely important for us to know what you think about this app. Please rate and review this app..
        /// </summary>
        public static string ReminderContent {
            get {
                return ResourceManager.GetString("ReminderContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip further reminders.
        /// </summary>
        public static string ReminderSkipFurther {
            get {
                return ResourceManager.GetString("ReminderSkipFurther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate My App.
        /// </summary>
        public static string ReminderSkipFurtherTitle {
            get {
                return ResourceManager.GetString("ReminderSkipFurtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        public static string ResizeTool {
            get {
                return ResourceManager.GetString("ResizeTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        public static string RotateTool {
            get {
                return ResourceManager.GetString("RotateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string SaturationTool {
            get {
                return ResourceManager.GetString("SaturationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off funny text on loading page.
        /// </summary>
        public static string SettingPageFunnyTextHeader {
            get {
                return ResourceManager.GetString("SettingPageFunnyTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise reduction (Increase open time).
        /// </summary>
        public static string SettingPageNoiseReductionHeader {
            get {
                return ResourceManager.GetString("SettingPageNoiseReductionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file format.
        /// </summary>
        public static string SettingPageSaveFileFormat {
            get {
                return ResourceManager.GetString("SettingPageSaveFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear cache.
        /// </summary>
        public static string SettingsClearCacheButton {
            get {
                return ResourceManager.GetString("SettingsClearCacheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing cache.
        /// </summary>
        public static string SettingsClearCacheProgressText {
            get {
                return ResourceManager.GetString("SettingsClearCacheProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto brightness.
        /// </summary>
        public static string SettingsPageAutoBrigtnessHeader {
            get {
                return ResourceManager.GetString("SettingsPageAutoBrigtnessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to delete.
        /// </summary>
        public static string SettingsPageDeleteAllFiles {
            get {
                return ResourceManager.GetString("SettingsPageDeleteAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half size image. Open image 4x faster.
        /// </summary>
        public static string SettingsPageHalfSizeHeader {
            get {
                return ResourceManager.GetString("SettingsPageHalfSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG export quality.
        /// </summary>
        public static string SettingsPageJpegQuality {
            get {
                return ResourceManager.GetString("SettingsPageJpegQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White balance from shot.
        /// </summary>
        public static string SettingsPageWhiteBalanceHeader {
            get {
                return ResourceManager.GetString("SettingsPageWhiteBalanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows.
        /// </summary>
        public static string ShadowsTool {
            get {
                return ResourceManager.GetString("ShadowsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness.
        /// </summary>
        public static string SharpnessTool {
            get {
                return ResourceManager.GetString("SharpnessTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string TemperatureTool {
            get {
                return ResourceManager.GetString("TemperatureTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully upgraded. Now you can edit photos in app..
        /// </summary>
        public static string UpgradeFinal {
            get {
                return ResourceManager.GetString("UpgradeFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 Professional Tools.
        /// </summary>
        public static string UpgradePage12Proff {
            get {
                return ResourceManager.GetString("UpgradePage12Proff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAWER EDIT PACK.
        /// </summary>
        public static string UpgradePageEditPack {
            get {
                return ResourceManager.GetString("UpgradePageEditPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ViewerPageAppBarAbout {
            get {
                return ResourceManager.GetString("ViewerPageAppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete file.
        /// </summary>
        public static string ViewerPageAppBarDelete {
            get {
                return ResourceManager.GetString("ViewerPageAppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ViewerPageAppBarEdit {
            get {
                return ResourceManager.GetString("ViewerPageAppBarEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ViewerPageAppBarExif {
            get {
                return ResourceManager.GetString("ViewerPageAppBarExif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ViewerPageAppBarSave {
            get {
                return ResourceManager.GetString("ViewerPageAppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ViewerPageAppBarShare {
            get {
                return ResourceManager.GetString("ViewerPageAppBarShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade app.
        /// </summary>
        public static string ViewerPageAppBarUpgrade {
            get {
                return ResourceManager.GetString("ViewerPageAppBarUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working....
        /// </summary>
        public static string ViewerPageLoaderMainText {
            get {
                return ResourceManager.GetString("ViewerPageLoaderMainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening and Processing….
        /// </summary>
        public static string ViewerPageLoaderText {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A camera&apos;s auto-focus works by comparing contrast between pixels. Sometimes rotating the camera can help achieve a better focus!.
        /// </summary>
        public static string ViewerPageLoaderText1 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the biggest lens that you can easily buy weighs 15 kg. and costs $ 26 000. Sigma 200-500 / 2.8.
        /// </summary>
        public static string ViewerPageLoaderText10 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most expensive photo is &quot;Standing in a circle&quot;, made by Jeff Frost, and was sold for $ 6.5 million on November 8, 2011..
        /// </summary>
        public static string ViewerPageLoaderText11 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canon name comes from the word Kwanon, in honor of the Buddhist deity of mercy with thousands of hands..
        /// </summary>
        public static string ViewerPageLoaderText12 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikon was originally the name of Nippon Kogaku, meaning &quot;Japanese optics&quot;..
        /// </summary>
        public static string ViewerPageLoaderText13 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best point for making a portrait is at eye level..
        /// </summary>
        public static string ViewerPageLoaderText14 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best point for making a full-lenght portrait is at waist level..
        /// </summary>
        public static string ViewerPageLoaderText15 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to crop the image so that the horizon line does not split the picture in half. The viewer will focus on the picture more easily..
        /// </summary>
        public static string ViewerPageLoaderText16 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When shooting a moving object (car, cyclist), always leave space in front of the object..
        /// </summary>
        public static string ViewerPageLoaderText17 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo sensors on the matrix of all cameras are black and white. Manufacturers use different methods, lenses and refraction of light to capture color..
        /// </summary>
        public static string ViewerPageLoaderText2 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get color on each sensor/pixel, manufacturers are using micro-lenses and prisms or color filters to refract light and send it to separate photo sensors of the corresponding color.
        /// </summary>
        public static string ViewerPageLoaderText3 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The larger the aperture is open or lower its value the less depth of field and more blurred background..
        /// </summary>
        public static string ViewerPageLoaderText4 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to place the main subject at the golden section. The main object should cover 2/3 of picture. People typically think such images are more beautiful..
        /// </summary>
        public static string ViewerPageLoaderText5 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first &quot;photo paper&quot; was made out of asphalt. Coated asphalt was varnished on a copper or glass plate..
        /// </summary>
        public static string ViewerPageLoaderText6 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos with three subjects have the effect of depth. On the foreground can be part of a tree, the second can be a person and the third - the sky or forest..
        /// </summary>
        public static string ViewerPageLoaderText7 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zoom function on a phone&apos;s cameras and other cheaper cameras is always composite. After a certain threshold, the camera just starts to magnify and crop the image digitally. It is better to disable the digital zoom. You can replicate the effect in post-processing while maintaining a higher-quality image..
        /// </summary>
        public static string ViewerPageLoaderText8 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The high-frequency color noise (photo from the phone) is much more effective to clean in YCbCr color mode than in RGB and others color modes..
        /// </summary>
        public static string ViewerPageLoaderText9 {
            get {
                return ResourceManager.GetString("ViewerPageLoaderText9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have not enough memory to open this image in full size. Do not worry we will try to open it in half size if you do not mind..
        /// </summary>
        public static string ViewerPageLowMemoryBody {
            get {
                return ResourceManager.GetString("ViewerPageLowMemoryBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip.
        /// </summary>
        public static string ViewerPageLowMemoryTitle {
            get {
                return ResourceManager.GetString("ViewerPageLowMemoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating image....
        /// </summary>
        public static string ViewerPageProgressBarTextSwap {
            get {
                return ResourceManager.GetString("ViewerPageProgressBarTextSwap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving picture.
        /// </summary>
        public static string ViewerPageProgressSavingTitle {
            get {
                return ResourceManager.GetString("ViewerPageProgressSavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to working....
        /// </summary>
        public static string ViewerPageProgressSharingTitle {
            get {
                return ResourceManager.GetString("ViewerPageProgressSharingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your picture is saved to phone &quot;Saved Pictures&quot; album..
        /// </summary>
        public static string ViewerPageSaveCompleted {
            get {
                return ResourceManager.GetString("ViewerPageSaveCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your picture is saved to phone.
        /// </summary>
        public static string ViewerPageSaveCompletedNotDefault {
            get {
                return ResourceManager.GetString("ViewerPageSaveCompletedNotDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade app to edit RAW photos right from your phone. Change contrast, exposure, brightness, saturation, sharpness, hue and etc..
        /// </summary>
        public static string ViewerPageTrialBody {
            get {
                return ResourceManager.GetString("ViewerPageTrialBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string ViewerPageTrialcontinueButton {
            get {
                return ResourceManager.GetString("ViewerPageTrialcontinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upgrade.
        /// </summary>
        public static string ViewerPageTrialOkButton {
            get {
                return ResourceManager.GetString("ViewerPageTrialOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string ViewerPageTrialTitle {
            get {
                return ResourceManager.GetString("ViewerPageTrialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIGNETTE.
        /// </summary>
        public static string VignettingTool {
            get {
                return ResourceManager.GetString("VignettingTool", resourceCulture);
            }
        }
    }
}
