//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageEditor.Resources.ResourceEditor", typeof(ResourceEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLUR.
        /// </summary>
        internal static string BlurTool {
            get {
                return ResourceManager.GetString("BlurTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BRIGHTNESS.
        /// </summary>
        internal static string BrightnessTool {
            get {
                return ResourceManager.GetString("BrightnessTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFFECTS.
        /// </summary>
        internal static string ColorEffectsTool {
            get {
                return ResourceManager.GetString("ColorEffectsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRAST.
        /// </summary>
        internal static string ContrastTool {
            get {
                return ResourceManager.GetString("ContrastTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CROP.
        /// </summary>
        internal static string CropTool {
            get {
                return ResourceManager.GetString("CropTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPOSURE.
        /// </summary>
        internal static string ExposureTool {
            get {
                return ResourceManager.GetString("ExposureTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIGHLIGHTS.
        /// </summary>
        internal static string HighlightsTool {
            get {
                return ResourceManager.GetString("HighlightsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HUE.
        /// </summary>
        internal static string HueTool {
            get {
                return ResourceManager.GetString("HueTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOISE.
        /// </summary>
        internal static string NoiseTool {
            get {
                return ResourceManager.GetString("NoiseTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESIZE.
        /// </summary>
        internal static string ResizeTool {
            get {
                return ResourceManager.GetString("ResizeTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATE.
        /// </summary>
        internal static string RotateTool {
            get {
                return ResourceManager.GetString("RotateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATURATION.
        /// </summary>
        internal static string SaturationTool {
            get {
                return ResourceManager.GetString("SaturationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHADOWS.
        /// </summary>
        internal static string ShadowsTool {
            get {
                return ResourceManager.GetString("ShadowsTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHARPNESS.
        /// </summary>
        internal static string SharpnessTool {
            get {
                return ResourceManager.GetString("SharpnessTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPERATURE.
        /// </summary>
        internal static string TemperatureTool {
            get {
                return ResourceManager.GetString("TemperatureTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIGNETTE.
        /// </summary>
        internal static string VignettingTool {
            get {
                return ResourceManager.GetString("VignettingTool", resourceCulture);
            }
        }
    }
}
